import type { Recipe } from "@foodos/types";

// Recetas demo. Cuando exista la tabla `recipes` en Supabase estas pasan a
// ser seed de base de datos (ver README, paso "Endurecer la sincronizacion").
export const DEMO_RECIPES: Recipe[] = [
  {
    id: "chicken-rice",
    title: "Bowl proteico de pollo",
    ingredients: ["pechuga", "arroz", "tomate"],
    kcal: 610,
    protein: 54,
    carbs: 72,
    fat: 12,
    cost: 3.8,
    image: "/images/recipe-chicken-bowl.webp",
    time: 25,
    servings: 1,
    difficulty: "fácil",
    tags: ["alta proteína", "rápida", "post-gym"],
    steps: [
      "Dora la pechuga en sartén con sal y especias.",
      "Calienta el arroz integral y saltea los tomates.",
      "Monta el bowl y ajusta la ración según tus macros.",
    ],
  },
  {
    id: "egg-toast",
    title: "Tostada de huevo y yogur",
    ingredients: ["huevo", "pan", "yogur"],
    kcal: 480,
    protein: 32,
    carbs: 48,
    fat: 18,
    cost: 2.4,
    image: "/images/recipe-egg-toast.webp",
    time: 12,
    servings: 1,
    difficulty: "muy fácil",
    tags: ["desayuno", "rápida", "vegetariana"],
    steps: [
      "Tuesta el pan y cocina el huevo a la plancha.",
      "Sirve el yogur con semillas o fruta.",
      "Ajusta sal y hierbas al gusto.",
    ],
  },
  {
    id: "tuna-pasta",
    title: "Pasta rápida con atún",
    ingredients: ["atun", "pasta", "tomate"],
    kcal: 690,
    protein: 42,
    carbs: 96,
    fat: 14,
    cost: 2.9,
    image: "/images/recipe-tuna-pasta.webp",
    time: 20,
    servings: 2,
    difficulty: "muy fácil",
    tags: ["económica", "rápida", "despensa"],
    steps: [
      "Cuece la pasta al dente.",
      "Mezcla tomate con atún y calienta a fuego suave.",
      "Integra pasta y salsa, termina con albahaca.",
    ],
  },
  {
    id: "lentils",
    title: "Lentejas de despensa",
    ingredients: ["lentejas", "arroz", "zanahoria"],
    kcal: 540,
    protein: 28,
    carbs: 92,
    fat: 7,
    cost: 1.8,
    image: "/images/recipe-lentils.webp",
    time: 35,
    servings: 2,
    difficulty: "fácil",
    tags: ["económica", "vegana", "alta fibra"],
    steps: [
      "Sofríe zanahoria y especias.",
      "Añade lentejas, arroz y agua o caldo.",
      "Cocina hasta que quede meloso y corrige de sal.",
    ],
  },
];
